### ISSUE TITLE
Trying to assign mac shortcut to /Symbol isn't working

### ISSUE THREAD

**Issue by josh-tt** [Ashung/Automate-Sketch#216]
Hi there, I'm trying to assign a Mac shorcut to items in the /Symbol menu and it's not working. Assigning shortcuts to other menus is. Not sure why that can be happening.

For example: 
Plugins->Automate->Symbol->Reset Overrides does not work (no key command from OS appears in sketch menu), but Plugins->Automate->Style->Paste Text Style works as do others.

Is it possible this is a bug in the plugin with regards to how the command is named on the front end?

**Comment by josh-tt** [comment]
Also, using Runner I can access those shortcuts, but they do not work. Posssibly related

**Comment by maxart2007** [comment]
Have same issue, trying to assign a shortcut to "Plugins->Automate->Symbol->Select All Instances of Symbol".

**Comment by Ashung** [comment]
Because Sketch Runner can't list all commands under Symbol or Symbols category, so I use a unicode character "ο"  to replace the "o" in symbol.

![image](https://user-images.githubusercontent.com/932544/67826142-86b69900-fb06-11e9-9c33-9595be9b8398.png)

Copy this `Plugins->Automate->Symbοl->Reset Overrides`
