### ISSUE TITLE
Change local layer styles to lib styles is broken

### ISSUE THREAD

**Issue by jansemka** [Ashung/Automate-Sketch#288]
I want to merge my local styles with that of an external lib. Atomate just recognized one of the around 5 or 6 colors to merge others doesn't appear in the list, screenshot attached.

Left the lib styles on the right the local file. You see the "success" green filled won't appear in the list.

![image](https://user-images.githubusercontent.com/13254959/94434182-aa141900-0199-11eb-9ebd-8c28bb5a9714.png)

**Comment by stephanie-walter** [comment]
Hi, same issue here: it's broken for layer styles, text styles and symbols.
All the styles exist since I copy paste some elements from the library, but this it changes to local style. When I want to use this plugin to bring styles back to the library one, it lists them properly but doesn't find them in the library I just copy pasted them from :(
